[package]
description = "A probe that enables test features on demand."
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-test-probe"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethcore = { path = "..", features = ["test-helpers"] }
