[package]
description = "Ethcore public test helpers"
homepage = "http://parity.io"
license = "GPL-3.0"
name = "ethcore-test-helpers"
version = "1.12.0"
authors = ["Parity Technologies <admin@parity.io>"]

[dependencies]
ethcore = { path = ".." }
